version: "3"

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24

services:
  namenode:
    image: lingoxp/hadoop-namenode:2.0.4-hadoop3.3.5-java8
    container_name: namenode
    hostname: namenode
    volumes:
      - namenode:/hadoop/dfs/name
      - '~/keys:/keys'
    environment:
      - CLUSTER_NAME=test
      - KRB5_REALM=DIPEAK.COM
      - KRB5_KDC=namenode
      - KRB5_PASS=111111
    networks:
      net:
        ipv4_address: 172.16.0.2

    env_file:
      - ./hadoop-hive.env
    ports:
      - "9870:9870"
      - "9000:9000"
      - "88:88"
      - "464:464"
      - "749:749"

  datanode:
    image: lingoxp/hadoop-datanode:2.0.4-hadoop3.3.5-java8
    hostname: datanode
    container_name: datanode
    volumes:
      - datanode:/hadoop/dfs/data
      - '~/keys:/keys'
    env_file:
      - ./hadoop-hive.env
    networks:
      net:
        ipv4_address: 172.16.0.3
    depends_on:
      - namenode
#      - HDFS_DATANODE_SECURE_USER=root
#      - JSVC_HOME=/opt/hadoop-3.3.5/libexec/




  resourcemanager:
    image: lingoxp/hadoop-resourcemanager:2.0.4-hadoop3.3.5-java8
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    volumes:
      - '~/keys:/keys'
    depends_on:
      - namenode
      - datanode
    env_file:
      - ./hadoop-hive.env
    networks:
      net:
        ipv4_address: 172.16.0.7

  nodemanager:
    image: lingoxp/hadoop-nodemanager:2.0.4-hadoop3.3.5-java8
    container_name: nodemanager
    hostname: nodemanager
    restart: always
    volumes:
      - '~/keys:/keys'
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    env_file:
      - ./hadoop-hive.env
    networks:
      net:
        ipv4_address: 172.16.0.8


  historyserver:
    image: lingoxp/hadoop-historyserver:2.0.4-hadoop3.3.5-java8
    hostname: historyserver
    container_name: historyserver
    environment:
      YARN_CONF_yarn_timeline-service_keytab: "/keys/historyserver.keytab"
      YARN_CONF_yarn_timeline-service_principal: "root/historyserver@DIPEAK.COM"
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    volumes:
      - historyserver:/hadoop/yarn/timeline
      - '~/keys:/keys'
    env_file:
      - ./hadoop-hive.env
    networks:
      net:
        ipv4_address: 172.16.0.9

  hive-server:
    image: lingoxp/hive:3.1.7-postgresql-metastore
    hostname: hive-server
    container_name: hive-server
    restart: always
    env_file:
      - ./hadoop-hive.env
    volumes:
      - '~/keys:/keys'
    environment:
      HIVE_SITE_CONF_hive_server2_transport_mode: "binary"
      HIVE_TYPE: "server"
    ports:
      - "10000:10000"
    networks:
      net:
        ipv4_address: 172.16.0.4
    depends_on:
      - nodemanager
      - hive-metastore
      - namenode


  hive-metastore:
    image: lingoxp/hive:3.1.7-postgresql-metastore
    hostname: hive-metastore
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    restart: always
    volumes:
      - '~/keys:/keys'
    environment:
      SERVICE_PRECONDITION: "namenode:9000"
      HIVE_TYPE: "metastore"
      HIVE_SITE_CONF_hive_metastore_local: "false"
    ports:
      - "9083:9083"
    networks:
      net:
        ipv4_address: 172.16.0.5
    depends_on:
      - nodemanager
      - namenode
      - hive-metastore-postgresql


  hive-metastore-postgresql:
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    image: mysql:8.0.33
    networks:
      net:
        ipv4_address: 172.16.0.6
    ports:
      - "3306:3306"


  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    ports:
      - "8080:8080"

  testenv:
    image: lingoxp/testenv:2.0.4-hadoop3.3.5-java8
    container_name: testenv
    hostname: testenv
    restart: always
    volumes:
      - '~/keys:/keys'
    depends_on:
      - namenode
      - datanode
    env_file:
      - ./hadoop-hive.env
    networks:
      net:
        ipv4_address: 172.16.0.10


volumes:
  namenode:
  datanode:
  historyserver:

